# Generated by Django 4.2.7 on 2026-03-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('signal_type', models.CharField(choices=[('BEARISH', 'Bearish'), ('BEARISH_TRAP', 'Bearish Trap'), ('BEARISH_ZONE', 'Bearish Zone'), ('BULLISH', 'Bullish'), ('BULLISH_PULLBACK', 'Bullish Pullback'), ('BULLISH_ZONE', 'Bullish Zone'), ('NEUTRAL', 'Neutral')], db_index=True, max_length=20)),
                ('strength', models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('WATCH', 'Watch'), ('-', 'None')], max_length=10)),
                ('reason', models.TextField()),
                ('ltp', models.FloatField()),
                ('phase', models.CharField(choices=[('PRE', 'Pre Market'), ('CANDLE', '5-Min Candle'), ('WATCH', 'Watch Window'), ('OPEN', 'Market Open')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to='market.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'signal_type'], name='signals_log_date_b83323_idx')],
            },
        ),
    ]
