# Generated by Django 4.2.7 on 2026-03-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(max_length=20)),
                ('strength', models.CharField(max_length=10)),
                ('ltp', models.FloatField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BEARISH', 'Bearish'), ('BEARISH_TRAP', 'Bearish Trap'), ('BULLISH', 'Bullish'), ('BULLISH_PULLBACK', 'Bullish Pullback'), ('ANY', 'Any Signal')], default='ANY', max_length=20)),
                ('only_strong', models.BooleanField(default=True, help_text='Sirf STRONG signals pe alert')),
                ('via_email', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, help_text='Null = all stocks', null=True, on_delete=django.db.models.deletion.CASCADE, to='market.stock')),
            ],
        ),
    ]
