# Generated by Django 4.2.7 on 2026-03-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('FALSE_ALERT_BULL', 'False Alert (was Bullish)'), ('FALSE_ALERT_BEAR', 'False Alert (was Bearish)'), ('NEUTRAL', 'Neutral')], db_index=True, max_length=20)),
                ('ltp_at_signal', models.FloatField()),
                ('oi_at_signal', models.BigIntegerField(default=0)),
                ('baseline_ltp', models.FloatField()),
                ('baseline_oi', models.BigIntegerField(default=0)),
                ('candle_high', models.FloatField(blank=True, null=True)),
                ('candle_low', models.FloatField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_logs', to='market.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock', 'date', 'signal_type'], name='market_sign_stock_i_72714d_idx')],
            },
        ),
    ]
